[package]
name = "enuminfo_macros"
version = "0.3.0"
authors = ["Dante Doménech <dante19031999@gmail.com>"]
description = "Procedural derive macros for enum inspection, string conversion, lookup, and variant enumeration."
readme = "README.md"
repository = "https://github.com/dante19031999/enuminfo-macros"
homepage = "https://dante19031999.github.io/enuminfo-macros/enuminfo_macros/index.html"
documentation = "https://docs.rs/enuminfo_macros"
license = "MIT OR Apache-2.0"
keywords = ["enum", "proc-macro", "derive", "case", "string"]
categories = ["development-tools::procedural-macro-helpers", "rust-patterns"]
edition = "2021"
rust-version = "1.70"
include = [
    "src/**/*",
    "tests/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]

[features]
default = ["from-str"]
impl-enuminfo = []
skip-inherent = []
from-str = []

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
heck = "0.5"

[dev-dependencies]
enuminfo = { version = "0.2.0" }